### ISSUE TITLE
Move to coala, rename to Git Task List

### ISSUE THREAD

**Issue by bekicot** [coala/git-task-list#29]
Back story:
```
As you are now required to work in coala repos, you should indicate in
your new project page whether you want "gsoc-prep-tasks" moved to
coala org, or a copy of the history imported to a new repository in
the coala org.

If you prefer a new repository with commits imported, please suggest a
name for the new repository.
```

I do not consent that this repo is moved to coala. As for now, it is part of coala's GSOC 2018 project to enhance this repository as described in https://github.com/coala/projects/commit/f5ca3b597f9693fd82e7e71072deda63abed701a.

@jayvdb

**Comment by jayvdb** [comment]
Done.  We'll move it back after the project ends.

**Comment by bekicot** [comment]
@jayvdb It is going to be part of Phase 1 Milestone
