### ISSUE TITLE
Use GraphQL

### ISSUE THREAD

**Issue by bekicot** [coala/git-task-list#34]
See Phase 1:
https://github.com/coala/projects/blob/master/_projects/git_task_list.md

Related Milestone:
https://gitlab.com/coala/GSoC/GSoC-2018/milestones/62

**Comment by blazeu** [comment]
Should be GraphQL

**Comment by bekicot** [comment]
@blazeu 
Can this reopen?
The commit and pull request has been edited, it was a mistake.
