### ISSUE TITLE
Use default deploy name & email

### ISSUE THREAD

**Issue by jayvdb** [coala/git-task-list#48]
`.travis.yml` includes

```yaml
  name: Yana Agun Siswanto
  email: yana.developer@gmail.com
```

The defaults are better as the generated commits are not extra work being done by anyone.

```yaml
  name: Deployment Bot
  email: deploy@travis-ci.org
```

**Comment by jayvdb** [comment]
Also possibly a good idea to use keep-history https://github.com/coala/gh-board/issues/52

**Comment by bhavya17037** [comment]
Hi, can I be assigned to this?
