### ISSUE TITLE
Add Project Style Rules

### ISSUE THREAD

**Issue by bekicot** [coala/git-task-list#58]
This project has no style rules and potentially have an unending debate about what is right.
It also confuses people to give a suggestion, @blazeu talked via gitter.

@blazeu recommends using AirBnB style Guides.

**Comment by jayvdb** [comment]
As you dont have a preferred style, we stick with AirBnB.

**Comment by jayvdb** [comment]
Decide on how it will be implemented.

Given how much of the codebase is going to be removed in the graphql patch, and large volumes of new code, it isnt sensible to fix all of the old code.

I suggest that the airbnb style is only enforced on the new files as part of the graphql patch.

Then latter a style fixup is done on all the other remaining files.
